import '@/app/ui/globals.css'
import type { Metadata } from 'next'
import { gabarito } from './ui/fonts'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={gabarito.className}>{children}</body>
    </html>
  )
}
