name: Workflow Pipeline

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci

  lint:
    needs: install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint

  build:
    needs: install
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build code
        run: npm run build

  deploy:
    needs: [install, build]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check if package.json has changed
        id: changed-package-json
        uses: tj-actions/changed-files@v44
        with:
          files: |
            package.json
      - name: Deploy with install
        if: steps.changed-package-json.outputs.any_changed == 'true'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.USER_SERVER }}
          password: ${{ secrets.PASSWORD_SERVER }}
          script: |
            cd /root/repos/web
            pm2 stop ecosystem.config.cjs
            git reset --hard HEAD
            git pull origin develop
            npm install
            npm run build
            pm2 restart ecosystem.config.cjs --env production
      - name: Deploy without install
        if: steps.changed-package-json.outputs.any_changed == 'false'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.USER_SERVER }}
          password: ${{ secrets.PASSWORD_SERVER }}
          script: |
            cd /root/repos/web
            pm2 stop ecosystem.config.cjs
            git reset --hard HEAD
            git pull origin develop
            npm run build
            pm2 restart ecosystem.config.cjs --env production
